apiVersion: v1
kind: Service
metadata:
  name: subscription-management-system-client
  labels:
    app: subscription-management-system-client
spec:
  selector:
    app: subscription-management-system-client
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-management-system-client
spec:
  selector:
    matchLabels:
      app: subscription-management-system-client
  replicas: 1
  strategy:    
    type: RollingUpdate
    rollingUpdate:     
      maxUnavailable: 0 
      maxSurge: 1  
  revisionHistoryLimit: 10
  
  template:
    metadata:
      name: subscription-management-system-client
      labels:
        app: subscription-management-system-client
    spec:
      containers:
        - name: subscription-management-system-client
          image: registry.gitlab.com/accto-ci-cd-version2/subscription-management-system:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            
          resources:
           requests:
             cpu: "100m"
             memory: "128Mi"
           limits:
             cpu: "500m"
             memory: "512Mi"

